version: '3'

networks:
  db_net:

services:

  app:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      
    networks:
      - db_net

  db:
    image: cassandra:latest
    networks:
      - db_net
     

